name: Angular

on:
  push:
    branches: [ develop ]
    paths:
      - 'ChatClient/Presentation/Client/Presentation.Client/**'
    
  pull_request:
    branches: [ develop ]
    paths:
      - 'ChatClient/Presentation/Client/Presentation.Client/**'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ChatClient/Presentation/Client/Presentation.Client
    
    - name: Test
      run: npm run test:ci
      working-directory: ChatClient/Presentation/Client/Presentation.Client
      
    - name: Build
      run: npm run build:ci
      working-directory: ChatClient/Presentation/Client/Presentation.Client
      

    
