name: Cypress Tests

on:
  push:
    branches: [ develop ]
    paths:
      - 'ChatClient/Presentation/Client/Presentation.Client/**'
    
  pull_request:
    branches: [ develop ]
    paths:
      - 'ChatClient/Presentation/Client/Presentation.Client/**'

  workflow_dispatch:

jobs:
  cypress-run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run End-to-end Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:ci
          start: npm run start:ci
        working-directory: ChatClient/Presentation/Client/Presentation.Client
    
      

    
